h2. a) Julkaise tämän kerran kotitehtävä GitHubissa, kirjoita raportti MarkDownilla. (Älä poista vanhoja weppisivujasi, linkitä tarvittaessa uuteen).
b) Asenna ja konfiguroi jokin palvelin package-file-service -tyyliin Puppetilla.

Tässä harjoituksessa on käytetty Debian Jessie 8.7 -käyttöjärjestelmää virtualbox -alustalla
Tarkoituksena asentaa Apache custom virtualhostilla käyttäen Puppetin templatea hyväksi.

Ensin asennetaan ja konffataan git:

apt-get install git

git config --global user.email “Juuso.lehtola@myy.haaga-helia.fi”
git config –global user.name ”Juuso Lehtola”

git init (kotihakemistoon)

git clone https://github.com/jupe150/laksyt.git

cd laksyt
nano laksyt.md

git commit

testiviesti:
Testing if my github connection actually works

git pull
git push

laitetaan käyttäjätunnus ja salasana ja enter

Ja se meni läpi.

Seuraavaksi tehdään template Puppettiin Apachen konffausta varten:

cd /etc/puppet/modules/apache/
mkdir templates
cd templates
nano testi.com.erb

Asetetaan sisältö templatelle:

Listen 8880
<VirtualHost *:8880>
     ServerAdmin admin@testi.com
     ServerName testi.com
     ServerAlias www.testi.com
     DocumentRoot /var/www/testi.com/
     ErrorLog /var/www/testi.com/logs/error.log
     CustomLog /var/www/testi.com/logs/access.log combined
</VirtualHost>

Seuraavaksi luodaan Puppet- moduuli muokkaamalla aiemmassa tehtävässä tehtyä moduulia:

        class apache {
        package {'apache2':
        ensure => installed ,
        allowcdrom => true ,
        }

        file { '/var/www/example.com':
        ensure => 'directory' ,
        require => Package['apache2'] ,
        groups => 'www-data',
        require => Group['www-data']
        before => Service['apache'],
        }

        file { '/var/www/example.com/index.html':
        ensure => 'file' ,
        require => Package['apache2'] ,
        content => 'trolololo'
        groups => 'www-data',
        require => Group['www-data']
        before => Service['apache'],
        }

        file { '/etc/apache2/sites-available/testi.com.conf':
        ensure  => 'file' ,
        content  => template("apache/testi.com.erb"),
        groups => 'www-data',
        require => Group['www-data']
        before => Service['apache'],
        }

        service { 'apache2':
        ensure => running ,
        enable => true ,
        require => Package['apache2']
}

Ajetaan puppet moduli, virheilmoitus:

Error: Could not parse for environment production: Could not match ‘class at line

Ilmeisesti oli vain komento väärin (kopioin vanhan komennon, niin hipsut muuttuivat vääränlaisiksi)

Seuraavaksi tällainen ajettaessa:

Error: Duplicate parameter 'require' for on File[/var/www/example.com] at /etc/puppet/modules/apache/manifests/init.pp:13 on node mylly

Johtui juurikin tuosta duplikaatista. Seuraava ongelma:

Error: Invalid parameter groups on File[/var/www/example.com] at /etc/puppet/modules/apache/manifests/init.pp:14 on node mylly

Eli group -parametrin perään oli livahtanu s-kirjain. Seuraava virhe:

Error: Could not find dependent Service[apache] for File[/var/www/example.com] at /etc/puppet/modules/apache/manifests/init.pp:14

Palvelun nimi väärin, sen pitäisi toki olla “apache2”.

Viimeinkin meni läpi, ja myöskin sivu toimii.

Lopullinen init.pp -tiedosto (kuten näkyy, muitakin muokkauksia tehty, kuin mitä edellä mainittu):

class apache {
        package {'apache2':
        ensure => installed ,
        allowcdrom => true ,
        }

        file { '/var/www/testi.com':
        ensure => 'directory' ,
        require => Package['apache2'] ,
        group => 'www-data',
        owner => 'root',
        mode => 0755,
        before => Service['apache2'],
        }

        file { '/var/www/testi.com/logs':
        ensure => 'directory' ,
        require => Package['apache2'] ,
        group => 'www-data',
        owner => 'root',
        mode => 0775,
        before => Service['apache2'],
        }

        file { '/var/www/testi.com/index.html':
        ensure => 'file' ,
        require => Package['apache2'] ,
        content => 'trolololo' ,
        group => 'www-data',
        owner => 'root',
        mode => 0755,
        before => Service['apache2'],
        }

        file { '/etc/apache2/sites-available/testi.com.conf':
        ensure  => 'file' ,
        content  => template("apache/testi.com.erb"),
        group => 'www-data',
        owner => 'root',
        mode => 0755,
        before => Service['apache2'],
        }

        service { 'apache2':
        ensure => running ,
        enable => true ,
        require => Package['apache2'],
}

}

Sivun enablointi vielä käsin (ei saanut toista samaa tiedostoa fileenä siten että toinen olisi ollut linkkinä):

a2ensite testi.com.conf

Sivu toimii.

Lähteet:

https://docs.puppet.com/puppet/latest/lang_relationships.html#packagefileservice
https://www.linode.com/docs/websites/apache/apache-web-server-debian-8
https://www.unixdaemon.net/puppet/simplifying-file-permissions-in-puppet-manifests/